services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: messagesLogin
      POSTGRES_PASSWORD: messagesPass
      POSTGRES_DB: messagesDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  web-api-messages:
    build:
      context: ../WebApiMessages
    ports:
      - "8001:8080"
    environment:
      DbSettings__Host: postgres
      DbSettings__Port: 5432
      DbSettings__Username: messagesLogin
      DbSettings__Password: messagesPass
      DbSettings__Database: messagesDb
      JwtSettings__SecretKey: qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
